databases:
  - name: library-db
    databaseName: library_system
    user: library_user
    plan: free

services:
  # Backend Service
  - type: web
    name: library-backend
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn librarySystemBackend.wsgi:application
    rootDir: backend
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: library-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      # - key: FRONTEND_URL
      #   fromService:
      #     name: library-frontend
      #     property: url
      - key: FRONTEND_URL
        value: https://library-y3p8.onrender.com

  # Frontend Service
  - type: web
    name: library
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    rootDir: frontend
    envVars:
      # - key: VITE_API_URL
      #   fromService:
      #     name: library-backend
      #     type: web
      #     property: url
      - key: VITE_API_URL
        value: https://library-backend-iys8.onrender.com

  # Automated Expiration Cron Job (suggested, not available in free plan)
  # - type: cron
  #   name: expire-reservations-cron
  #   env: python
  #   schedule: "*/5 * * * *" # Every 5 minutes
  #   buildCommand: pip install -r requirements.txt
  #   startCommand: python manage.py expire_reservations
  #   rootDir: backend
  #   plan: starter
  #   envVars:
  #     - key: DATABASE_URL
  #       fromDatabase:
  #         name: library-db
  #         property: connectionString
  #     - key: SECRET_KEY
  #       fromService:
  #         name: library-backend
  #         type: web
  #         property: envVar:SECRET_KEY
  #     - key: DEBUG
  #       value: "False"
