import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import api from '../services/api';

export interface Book {
  id: string;
  title: string;
  author: string;
  isbn: string | null;
  is_active: boolean;
  available_copies_count: number;
  total_copies_count: number;
  can_delete: boolean;
  created_at: string;
  updated_at: string;
}

// Omit the fields that are generated by the backend
export type BookFormData = Omit<Book, 'id' | 'is_active' | 'available_copies_count' | 'total_copies_count' | 'can_delete' | 'created_at' | 'updated_at'> & {
  copies_count?: number;
};

export const useBooks = () => {
  const queryClient = useQueryClient();

  const fetchBooks = async (): Promise<Book[]> => {
    const { data } = await api.get('/books/');
    return data;
  };

  const createBook = async (bookData: BookFormData): Promise<Book> => {
    const { data } = await api.post('/books/', bookData);
    return data;
  };

  const updateBook = async ({ id, ...bookData }: { id: string } & Partial<BookFormData>): Promise<Book> => {
    const { data } = await api.patch(`/books/${id}/`, bookData);
    return data;
  };

  const deleteBook = async (id: string): Promise<void> => {
    await api.delete(`/books/${id}/`);
  };

  const booksQuery = useQuery({
    queryKey: ['books'],
    queryFn: fetchBooks,
  });

  const createMutation = useMutation({
    mutationFn: createBook,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['books'] });
    },
  });

  const updateMutation = useMutation({
    mutationFn: updateBook,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['books'] });
    },
  });

  const deleteMutation = useMutation({
    mutationFn: deleteBook,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['books'] });
    },
  });

  return {
    books: booksQuery.data || [],
    isLoading: booksQuery.isLoading,
    error: booksQuery.error,
    createBook: createMutation.mutateAsync,
    isCreating: createMutation.isPending,
    updateBook: updateMutation.mutateAsync,
    isUpdating: updateMutation.isPending,
    deleteBook: deleteMutation.mutateAsync,
    isDeleting: deleteMutation.isPending,
  };
};
