# Generated by Django 5.2.13 on 2026-04-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarySystemBackend', '0002_book_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('borrowed', 'Borrowed'), ('pending_transfer', 'Pending Transfer'), ('deleted_by_librarian', 'Deleted by Librarian')], default='available', max_length=20),
        ),
    ]
