# Generated by Django 5.2.13 on 2026-04-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarySystemBackend', '0003_alter_bookcopy_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='transferrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
