# Generated by Django 5.2.13 on 2026-04-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarySystemBackend', '0004_loan_updated_at_reservation_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('fiction', 'Ficción'), ('mystery', 'Misterio'), ('scifi', 'Ciencia Ficción'), ('fantasy', 'Fantasía'), ('romance', 'Romance'), ('horror', 'Terror'), ('biography', 'Biografía'), ('history', 'Historia'), ('poetry', 'Poesía'), ('drama', 'Drama')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'author')},
        ),
    ]
