# Generated by Django 5.2.13 on 2026-04-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarySystemBackend', '0005_book_description_book_genre_book_publication_year_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('fiction', 'Ficción'), ('non_fiction', 'No Ficción'), ('mystery', 'Misterio'), ('sci_fi', 'Ciencia Ficción'), ('fantasy', 'Fantasía'), ('biography', 'Biografía'), ('history', 'Historia'), ('romance', 'Romance'), ('horror', 'Terror'), ('classics', 'Clásicos')], max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique_book_title_author'),
        ),
    ]
