# Generated by Django 5.2.13 on 2026-04-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarySystemBackend', '0006_alter_book_unique_together_alter_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='book',
            name='unique_book_title_author',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique_book_title_author', violation_error_message='Ya existe un libro con este título y autor en el catálogo.'),
        ),
    ]
